[project]
name = "checkdeps"
version = "0.1.0"
description = "No-extra-deps python script that checks versions of installed software."
authors = [{ name = "Johan Hidding", email = "j.hidding@esciencecenter.nl" }]
requires-python = "~=3.10"
license = "Apache-2.0"

[dependency-groups]
dev = [
    "pdoc>=15",
    "numpy>=2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
